/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.Departments;
import Modele.Employees;
import Modele.Locations;
import Utils.HibernateUtil;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javassist.CtMethod.ConstParameter.string;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Administrateur
 */
public class FenTP extends javax.swing.JFrame {

    /**
     * Creates new form FenTP
     */
    public FenTP() {
        initComponents();
    }
    private static String query_first_name
            = "from Employees e where e.firstName like '";
    private static String query_last_name = "from Employees e where e.lastName like '";

    //crrer la requete pour firstname
    private void runQueryFirstName() {
        executeHQLQuery(query_first_name + champPrenom.getText() + "%'");
    }

    //créer la requete pour lastname
    private void runQueryLastName() {
        executeHQLQuery(query_last_name + champNom.getText() + "%'");
    }
    //executer requete HQL

    private void executeHQLQuery(String query) {

        try {
            Session session = Utils.HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            Query q = session.createQuery(query);
            List resultat = q.list();
            afficherResultat(resultat);
            session.getTransaction().commit();

        } catch (HibernateException he) {
            he.printStackTrace();
        }
    }

    private void afficherResultat(List listing) {
        Vector<String> enteteTable = new Vector<String>();
        Vector donneesTable = new Vector();
        //initialiser les entetes avec le bin texte

        enteteTable.add("Prénom");
        enteteTable.add("Nom");
        enteteTable.add("Date Embauche");
        enteteTable.add("Salaire");

        //remplir la table une ligne a la fois
        for (Object o : listing) {
            Employees emp = (Employees) o;
            //mettre le contenu dans une ligne de la table
            Vector<Object> ligne = new Vector<Object>();
            ligne.add(emp.getFirstName());
            ligne.add(emp.getLastName());
            ligne.add(emp.getHireDate());
            ligne.add(emp.getSalary());
            //ajouter la ligne dans table UI
            donneesTable.add(ligne);
        }
        table.setModel(new DefaultTableModel(donneesTable, enteteTable));

    }

    public void remplirCombLoc() {
        Session session = Utils.HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query qE = session.getNamedQuery("queryEmp");
        Query qD = session.getNamedQuery("queryDep");
        Query qJ = session.getNamedQuery("queryEmpJob");

        Query q = session.getNamedQuery("queryLocaltion");

        List listeE = qE.list();
        List listeD = qD.list();
        List listeL = q.list();
        List listeJ = qJ.list();

        champIdLoc.removeAllItems();
        for (Object o : listeL) {
            Locations loc = (Locations) o;
            champIdLoc.addItem(loc.getLocationId() + "-" + loc.getCity());

        }
        champDepEmp.removeAllItems();

        for (Object o : listeD) {
            Departments dep = (Departments) o;
            champDepEmp.addItem(dep.getDepartmentId() + "-" + dep.getDepartmentName());

        }
        champIdMan.removeAllItems();
        champManEMP.removeAllItems();
        champIdMan.addItem("");
        champManEMP.addItem("");

        for (Object o : listeE) {
            Employees emp = (Employees) o;
            champIdMan.addItem(emp.getEmployeeId() + "-" + emp.getFirstName() + ", " + emp.getLastName());
            champManEMP.addItem(emp.getEmployeeId() + "-" + emp.getFirstName() + ", " + emp.getLastName());
            //champJobEmp.addItem(emp.getJobId());
        }
        champJobEmp.removeAllItems();

        for (int i = 0; i < listeJ.size(); i++) {
            champJobEmp.addItem(listeJ.get(i));

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        champNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        champPrenom = new javax.swing.JTextField();
        btnAnnuler = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        btnRecherche = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        champNameDep = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        champIdMan = new javax.swing.JComboBox();
        champIdLoc = new javax.swing.JComboBox();
        btnAjouterDep = new javax.swing.JButton();
        btnAnnulerDep = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        champNomEmp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        champPrenomEmp = new javax.swing.JTextField();
        champEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        champDateE = new javax.swing.JTextField();
        champJobEmp = new javax.swing.JComboBox();
        champSalaire = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        champManEMP = new javax.swing.JComboBox();
        champDepEmp = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        btnAnnulerE = new javax.swing.JButton();
        btnAjouterE = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane2.setToolTipText("");

        jLabel1.setText("Prénom");

        champNom.setToolTipText("");

        jLabel2.setText("Nom");

        btnAnnuler.setText("Annuler");
        btnAnnuler.setToolTipText("");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Prénom", "Nom", "Date Embauche", "Salaire"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Détails Employé");

        btnRecherche.setText("Recherche");
        btnRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(champPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(champNom, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(champPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(champNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Recherche", jPanel6);

        jPanel7.setToolTipText("");

        jLabel4.setText("Nom Departement");

        jLabel5.setText("Manager");

        jLabel6.setText("Location");

        champIdMan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        champIdLoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAjouterDep.setText("Ajouter");
        btnAjouterDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterDepActionPerformed(evt);
            }
        });

        btnAnnulerDep.setText("Annuler");
        btnAnnulerDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerDepActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Ajouter Département");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btnAjouterDep)
                                .addGap(41, 41, 41)
                                .addComponent(btnAnnulerDep))
                            .addComponent(champIdMan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(champIdLoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(champNameDep, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel13)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(champNameDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(champIdMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(champIdLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterDep)
                    .addComponent(btnAnnulerDep))
                .addGap(113, 113, 113))
        );

        jTabbedPane2.addTab("Dépatement", jPanel7);

        jLabel3.setText("Nom");

        champNomEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                champNomEmpActionPerformed(evt);
            }
        });

        jLabel7.setText("Prénom");

        jLabel8.setText("Email");

        jLabel10.setText("Date d'embauche");

        champJobEmp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Salaire");

        jLabel14.setText("Manager");

        champManEMP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        champDepEmp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setText("Departement");

        btnAnnulerE.setText("Annuler");
        btnAnnulerE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerEActionPerformed(evt);
            }
        });

        btnAjouterE.setText("Ajouter");
        btnAjouterE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterEActionPerformed(evt);
            }
        });

        jLabel11.setText("Job Employe");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Ajouter Employé");

        jLabel17.setText("JJ-MM-AAAA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(btnAjouterE)
                                .addGap(77, 77, 77))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(champNomEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(champEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(champDateE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(champManEMP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                        .addComponent(jLabel17)))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(btnAnnulerE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(champDepEmp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(champSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(champPrenomEmp)
                                        .addComponent(champJobEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(champNomEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(champPrenomEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(champEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(champJobEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(champDateE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(champSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(champManEMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(champDepEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterE)
                    .addComponent(btnAnnulerE))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Employé", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        // TODO add your handling code here:
        champNom.setText("");
        champPrenom.setText("");
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0);
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnAjouterDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterDepActionPerformed
        // TODO add your handling code here:

        if (champNameDep.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vous-devez entrer le nom de département S.V.P !", "Erreur de saisie", JOptionPane.INFORMATION_MESSAGE);

        } else {
            String[] tokens = new String[2];

            String locationD = champIdLoc.getSelectedItem().toString();
            tokens = locationD.split("-");
            int idLoc = Integer.parseInt(tokens[0]);
            String ville = tokens[1];

            // Créer objets session et transaction
            java.util.logging.Logger.getLogger("org.hibernate").setLevel(Level.SEVERE);
            Session session = HibernateUtil.currentSession();
            Transaction tx = session.beginTransaction();

            Locations location = new Locations((short) idLoc, ville);

            Departments dep = new Departments();
            dep.setDepartmentName(champNameDep.getText());
            dep.setLocations(location);
            String mangerD = champIdMan.getSelectedItem().toString();

            if (!mangerD.isEmpty()) {
                tokens = mangerD.split("-");
                int idMan = Integer.parseInt(tokens[0]);
                Employees employe = new Employees(idMan);
                dep.setEmployees(employe);

            }

            session.saveOrUpdate(dep);
            tx.commit();
            remplirCombLoc();
            champNameDep.setText("");
            JOptionPane.showMessageDialog(null, "Ajout avec succès", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAjouterDepActionPerformed

    private void btnAjouterEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterEActionPerformed
        // TODO add your handling code here:
        /**
         * **************Employees**************
         */
        if (champNomEmp.getText().isEmpty() || champPrenomEmp.getText().isEmpty() || champEmail.getText().isEmpty()
                || champSalaire.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Vous-devez remplir tous les chmps S.V.P !", "Erreur de saisie", JOptionPane.INFORMATION_MESSAGE);
        } else {

            String[] tokens = new String[2];

            String depEmp = champDepEmp.getSelectedItem().toString();
            tokens = depEmp.split("-");
            int idDepEmp = Integer.parseInt(tokens[0]);
            //System.out.println(idDepEmp);

            String jobEmp = champJobEmp.getSelectedItem().toString();

            Employees emp = new Employees();
            emp.setFirstName(champPrenomEmp.getText());
            emp.setLastName(champNomEmp.getText());

            DateFormat format = new SimpleDateFormat("dd-mm-yyyy");
            Date date;

            try {
                date = format.parse(champDateE.getText());
                emp.setHireDate(date);
            } catch (ParseException ex) {
                //Logger.getLogger(FenTP.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "date invalide !", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
            }
            if (!Utils.Utils.isDouble(champSalaire.getText())) {
                JOptionPane.showMessageDialog(null, "Salaire invalide !", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
            } else {
                BigDecimal b = new BigDecimal(champSalaire.getText());

                emp.setSalary(b);

                emp.setJobId(jobEmp);
                Departments dep = new Departments();
                dep.setDepartmentId((short) idDepEmp);
                emp.setDepartments(dep);
                int idManEmp;
                String manEmp = champManEMP.getSelectedItem().toString();
                if (!manEmp.isEmpty()) {
                    tokens = manEmp.split("-");
                    idManEmp = Integer.parseInt(tokens[0]);

                    Employees manager = new Employees();
                    manager.setEmployeeId(idManEmp);
                    emp.setEmployees(manager);

                }
                // Créer objets session et transaction
                java.util.logging.Logger.getLogger("org.hibernate").setLevel(Level.SEVERE);
                Session session = HibernateUtil.currentSession();

                try {
                    if (HibernateUtil.isEmailAdress(champEmail.getText())) {
                        emp.setEmail(champEmail.getText());
                        Transaction tx = session.beginTransaction();
                        session.saveOrUpdate(emp);
                        tx.commit();
                        JOptionPane.showMessageDialog(null, "Ajout avec succès", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
                        remplirCombLoc();
                        champNomEmp.setText("");
                        champPrenomEmp.setText("");
                        champEmail.setText("");
                        champDateE.setText("");
                        champSalaire.setText("");

                    } else {
                        JOptionPane.showMessageDialog(null, "email invalide !", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "email invalide !", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
                }

            }
        }

    }//GEN-LAST:event_btnAjouterEActionPerformed

    private void champNomEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_champNomEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_champNomEmpActionPerformed

    private void btnAnnulerDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerDepActionPerformed
        // TODO add your handling code here:
        champNameDep.setText("");
    }//GEN-LAST:event_btnAnnulerDepActionPerformed

    private void btnAnnulerEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerEActionPerformed
        // TODO add your handling code here:
        champNomEmp.setText("");
        champPrenomEmp.setText("");
        champEmail.setText("");
        champDateE.setText("");
        champSalaire.setText("");
    }//GEN-LAST:event_btnAnnulerEActionPerformed

    private void btnRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercheActionPerformed
        // TODO add your handling code here:

        if (champPrenom.getText().trim().equals("") && champNom.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Vous-devez entrer un nom ou un prénom S.V.P !", "Erreur de saisie", JOptionPane.INFORMATION_MESSAGE);
        }
        if (!champPrenom.getText().trim().equals("")) {
            runQueryFirstName();
        } else if (!champNom.getText().trim().equals("")) {
            runQueryLastName();
        }
    }//GEN-LAST:event_btnRechercheActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterDep;
    private javax.swing.JButton btnAjouterE;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnAnnulerDep;
    private javax.swing.JButton btnAnnulerE;
    private javax.swing.JButton btnRecherche;
    private javax.swing.JTextField champDateE;
    private javax.swing.JComboBox champDepEmp;
    private javax.swing.JTextField champEmail;
    private javax.swing.JComboBox champIdLoc;
    private javax.swing.JComboBox champIdMan;
    private javax.swing.JComboBox champJobEmp;
    private javax.swing.JComboBox champManEMP;
    private javax.swing.JTextField champNameDep;
    private javax.swing.JTextField champNom;
    private javax.swing.JTextField champNomEmp;
    private javax.swing.JTextField champPrenom;
    private javax.swing.JTextField champPrenomEmp;
    private javax.swing.JTextField champSalaire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
